[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  # Do not omit dev dependencies during install so build plugins are available
  NPM_FLAGS = ""
